name: fastgym_mobile
description: "fastgym app for sport users and gym users."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  # para firebase (login) | cuando no se pone nada, trae las ultimas versiones



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:

      # vista
     - ./assets/image/cielo.png
     - ./assets/image/breakfast.png
     - ./assets/image/lunch.png
     - ./assets/image/dinner.png

     # vista alimentacion:
     - ./assets/image/icon_egghardboiled.png
     - ./assets/image/emoji_poultryleg.png
     - ./assets/image/illustration_Salad.png

     # vista consejos
     - ./assets/image/grafric.png
     - ./assets/image/gatorade.png

     # vista plan
     - ./assets/image/Flaco.jpg
     - ./assets/image/Medium.jpg
     - ./assets/image/Fat.jpg

     # vista tipo de usuario
     - ./assets/image/adult-bar.jpg
     - ./assets/image/adult-run.jpg

     # welcome
     - ./assets/image/fastgym-logo.png

    # profile
     - ./assets/image/profile-edit.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
